"""empty message

Revision ID: 5ef196c1708d
Revises: 2c262340861c
Create Date: 2022-05-03 10:39:44.993546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef196c1708d'
down_revision = '2c262340861c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=260), nullable=True),
    sa.Column('type', sa.String(length=260), nullable=True),
    sa.Column('categories', sa.String(length=260), nullable=False),
    sa.Column('author', sa.String(length=260), nullable=True),
    sa.Column('pages', sa.String(length=260), nullable=True),
    sa.Column('content', sa.String(length=260), nullable=False),
    sa.Column('img_reference', sa.String(length=260), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
