"""empty message

Revision ID: 7264552c70af
Revises: 
Create Date: 2022-04-26 10:49:13.583888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7264552c70af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('example', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=260), nullable=False),
    sa.Column('categories', sa.String(length=210), nullable=False),
    sa.Column('tags', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussion')
    # ### end Alembic commands ###
