"""empty message

Revision ID: 907b20af270b
Revises: 5ef196c1708d
Create Date: 2022-05-12 11:19:37.858513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907b20af270b'
down_revision = '5ef196c1708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usercourse', sa.Column('author', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercourse', 'author')
    # ### end Alembic commands ###
